### ISSUE TITLE
Allow permission check on collection of resources

### ISSUE THREAD

**Issue by cmgreen210** [holgi/fastapi-permissions#3]
If I'm not mistaken permissions can only be checked on a single resource. When implementing a bulk api it would be very convenient to be able to check permissions on a list of resources all at once:

```python
def update_items(items: List[Item]=Permission("edit", get_items), body: ...):
    ...
```

**Comment by holgi** [comment]
Thanks for the feature request. 
I have an idea on how to implement it, but please bear with me if I need some time to get to this.

**Comment by dieros** [comment]
Hi @holgi ! First of all, thanks for sharing this project, it's reeeally interesting for some work i'm doing with FastApi.
Do you have any update about this? 
I will face some issues regarding this in near future, and before getting hands on your source, I'd like to know if you have some progress done.
Thanks!

**Comment by holgi** [comment]
Dear @cmgreen210 and @diegorosen, I apologize that it took me longer to come back to this topic as I expected - some real life events got in my way.

I do have a working implementation of this request but I'm very unhappy with it. Not from a coding perspective but from the design perspective and in what direction it is progressing.

It boils down to a couple of points that are not easily answered from a library perspective:


_What should happen if only some items of the collection don't have the correct permissions?_

There are two ways of handling this and both might be the right way depending on the situation:

1. Invalidate the complete request if one or more items have incorrect permissions. This is a valid approach, if the operation must be atomic, like updating an account balance.
2. Filter out the items that don't have the right permissions. This might be valid if, for example, you update the "published" status of some articles and another user modified the status in the meantime.

I think in both occasions raising a "Forbidden Error" for the complete request is not the right error message to the user - it should probably be more verbose and tailored to the item(s) that have an issue.


_How about other iterables beside lists?_

Other iterables might also be returned. The handling of tuples or custom iterables is probably fine, but what about dicts? Should the key or the value be checked for permissions - probably the value, but it could be both. And what about generators, especially looping or infinite ones?


_The ability to check if a user is entitled for batch operations is lost_

With the suggested changes, the possibility to check if a user is allowed to perform a batch operation at all is lost.


So from a design perspective, I would not like to publish this changes. In my opinion, the check for permissions in batch operations is more a "business logic" thing that belongs into the function and is not so much about accessing the endpoint itself.


I would suggest to implement batch operations and permission checks along these (incomplete) examples:

```python

from fastapi_permissions import configure_permissions, has_permission, Allow

# must be provided
def get_active_principals(...):
    """ returns the principals of the current logged in user"""
    ...

# Permission is alredy wrapped in Depends()
Permission = configure_permissions(get_active_principals)

# allow batch operations only for the editor role
AclBatchPermission = [(Allow, "role:editor", "batch")]


async def atomic_operation(
	items: List[Item]=Depends(get_items),
	principals: list=Depends(get_active_principals),
	acls:list=Permission("batch", AclBatchPermission)
	):

	if not all(has_permission(principals, "edit", item) for item in items):
		raise SomeCustomError()


async def filter_operation(
	items: List[Item]=Depends(get_items),
	principals: list=Depends(get_active_principals),
	acls:list=Permission("batch", AclBatchPermission)
	):

	allowed = [item for item in items if has_permission(principals, "edit", item)]


```

I hope, that this decision is acceptable for you.

**Comment by holgi** [comment]
This was now open for discussion for a couple of weeks. I'll close this issue as "won't fix" since nobody seems to complain about my decision. Thanks for the question in the first place.
